Repository Syntax-Samurais/Website, pull requests merged in 2024-02, with the labels that each got.

#2 Bolier plate
  .github/workflows/nextjs-deployment.yml
  .github/workflows/prettier.yml
  .husky/pre-commit
  README.md
  Test file
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  public/next.svg
  public/vercel.svg
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  tailwind.config.js
Labels: enhancement

#4 Color pallete and page deployment
  .github/workflows/nextjs.yml
  README.md
Labels: documentation, enhancement

#5 Landing page
  package-lock.json
  package.json
  public/images/Testimonial_pfp.jpg
  public/images/mountains.jpeg
  src/app/_modals/LoginModal.jsx
  src/app/_modals/SignUpModal.jsx
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
Labels: enhancement

#6 Attempt 2
  .github/workflows/nextjs.yml
Labels: help wanted

#7 Page deploy
  .github/workflows/nextjs.yml
  public/next.svg
  public/vercel.svg
Labels: enhancement

#9 Cardio page
  public/images/logo1.png
  public/images/mountains2.jpeg
  src/app/_components/_header.jsx
  src/app/_components/_modals/LoginModal.jsx
  src/app/_components/_modals/SignUpModal.jsx
  src/app/cardio/cardio.css
  src/app/cardio/page.js
  src/app/dashboard/dashboard.css
  src/app/dashboard/page.js
  src/app/page.js
Labels: enhancement

#8 Header Completion
  public/images/logo1.png
  public/images/mountains2.jpeg
  src/app/_components/_header.jsx
  src/app/_components/_modals/LoginModal.jsx
  src/app/_components/_modals/SignUpModal.jsx
  src/app/cardio/cardio.css
  src/app/cardio/page.js
  src/app/dashboard/dashboard.css
  src/app/dashboard/page.js
  src/app/page.js
Labels: enhancement

#13 style refining for navbar
  src/app/_components/NavBar.jsx
Labels: enhancement

#15 Styled modal
  .github/workflows/nextjs-deployment.yml
  src/app/_components/_modals/LoginModal.jsx
  src/app/cardio/page.js
Labels: enhancement

#20 Sign up page
  db/migration.sql
  src/app/SignUp/page.js
  src/app/api/SignUp/route.js
  src/app/page.js
  tailwind.config.js
Labels: enhancement

#23 Working pie and line charts
  src/app/Home/page.js
  src/app/_components/LineChart.js
  src/app/_components/PieChart.js
  src/app/_components/_modals/LoginModal.jsx
Labels: enhancement

#24 Cardio page
  src/app/_components/NavBar.jsx
  src/app/api/Cardio/route.js
  src/app/cardio/page.js
Labels: enhancement

#29 Anthony
  db/migration.sql
  src/app/_components/AlertBox.jsx
  src/app/api/Cardio/route.js
  src/app/cardio/cardio.css
  src/app/cardio/page.js
  src/app/globals.css
  src/app/page.js
  tailwind.config.js
Labels: enhancement

#27 Sign up page
  src/app/SignUp/page.js
  src/app/api/SignUp/route.js
  src/app/page.js
Labels: enhancement

#31 Goals 2
  src/app/api/Goals/route.js
  src/app/goals/page.js
Labels: enhancement

#32 Update page.js
  src/app/Diet/page.js
Labels: enhancement

#33 style fix for goals page
  src/app/cardio/page.js
  src/app/goals/goals.css
  src/app/goals/page.js
Labels: enhancement
